[package]
name = "SnekPlanet"
version = "0.2.0"
edition = "2021"

[dependencies]
iron_planet = "0.2.1"

[lib]
name = "supernova"
crate_type = ["cdylib"]

[dependencies.pyo3]
version = "0.15.0"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
